from typing import Protocol, Any, Optional

from dtos.base import BaseDto


class BaseRepository[T](Protocol):
    def create(self, dto: BaseDto) -> T: ...

    def read_by_id(self, id: Any) -> Optional[T]: ...

    def read_all(self) -> list[T]: ...

    def update(self, id: Any, dto: BaseDto) -> Optional[T]: ...

    def delete(self, id: Any) -> Optional[T]: ...
